#!/command/with-contenv sh
set -eu

exec /usr/sbin/rtpengine \
  --foreground \
  --table=-1 \
  --interface=0.0.0.0 \
  --listen-ng=127.0.0.1:2223 \
  --port-min="${RTPENGINE_MIN_PORT}" \
  --port-max="${RTPENGINE_MAX_PORT}"
