#!/command/with-contenv sh
set -eu

RTPENGINE_BIN="$(command -v rtpengine || true)"
if [ -z "$RTPENGINE_BIN" ]; then
  RTPENGINE_BIN="/usr/sbin/rtpengine"
fi

exec "$RTPENGINE_BIN" \
  --foreground \
  --table=-1 \
  --interface=127.0.0.1 \
  --listen-ng=127.0.0.1:2223 \
  --port-min="${RTPENGINE_MIN_PORT}" \
  --port-max="${RTPENGINE_MAX_PORT}"
